language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

install:
  - COMPOSER_ROOT_VERSION=dev-master composer install --prefer-source

before_script:
  - composer install --dev

script: sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" -o "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then rm phpspec.yml && vendor/bin/phpspec run; else vendor/bin/phpspec run; fi;'

after_script: sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then vendor/bin/coveralls -v; fi;'
